name: "Support Request / Bug Report"
title: "[SUPPORT] "
labels: support
body:
  - type: markdown
    attributes:
      value: |
        **Description**
        Please describe the issue in detail.

  - type: input
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue
      placeholder: "1. \n2. \n3."
      required: false

  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen
      placeholder: ""
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Links
      description: Provide screenshots or links if any
      placeholder: ""
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, etc.
      placeholder: ""
      required: false
