.github/ISSUE_TEMPLATE/support.yml
```yaml
name: "Support Request / Bug Report"
description: "Use this form to request support or report a bug."
title: "[SUPPORT] "
labels: [support]
body:
  - type: markdown
    attributes:
      value: "**Please provide the details of your support request or bug below.**"

  - type: input
    id: short_summary
    attributes:
      label: "Short Summary"
      description: "Write a short summary of your issue."
      placeholder: "Example: Unable to access my wallet"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Detailed Description"
      description: "Describe your issue in detail so our GitHub Interact team can understand it."
      placeholder: "Include all relevant details, screenshots, or messages."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List steps that lead to the issue."
      placeholder: "1. Go to...
2. Click...
3. Error appears..."

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe what you expected"

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Browser, OS, device, or version info."
      placeholder: "Example: Chrome 120 on Windows 11"

