name: "Support Request / Bug Report"
title: "[SUPPORT] "
labels: support
body:
- type: markdown
attributes:
value: |
**Please provide the details of your support request or bug below.**


- type: textarea
id: description
attributes:
label: Description
description: Describe your issue in detail so our GitHub Interact team can assist.
placeholder: "Provide all relevant details, error messages, and what you tried so far."


- type: textarea
id: steps_to_reproduce
attributes:
label: Steps to Reproduce
description: List the steps to reproduce the issue
placeholder: "Step 1, Step 2, Step 3"


- type: textarea
id: expected_behavior
attributes:
label: Expected Behavior
description: What you expected to happen
placeholder: "Describe what you expected"


- type: textarea
id: environment
attributes:
label: Environment
description: Browser, OS, etc.
placeholder: "e.g., Chrome 120 on Windows 11"
